
# pull official base image
FROM python:3.9-slim-buster

# set work directory
WORKDIR /usr/src/app

# create the app user
RUN addgroup --system app && adduser --system --group app

# set environment variables
# Prevents Python from writing pyc files to disc
ENV PYTHONDONTWRITEBYTECODE 1
# Prevents Python from buffering stdout and stderr
ENV PYTHONUNBUFFERED 1

# install psycopg2 dependencies
RUN apt-get update \
  && apt-get -y install gcc postgresql \
  && apt-get clean

# install dependencies
RUN pip install --upgrade pip
COPY ../requirements-dev.txt .
RUN pip install -r requirements-dev.txt

# copy project
COPY . .